export const footerLinks = [
	{text: 'FAQ', link: 'faq'},
	{text: 'Help Center', link: 'help-center'},
	{text: 'Account', link: 'account'},
	{text: 'Media Center', link: 'media-center'},
	{text: 'Investor Relations', link: 'investor-relations'},
	{text: 'Jobs', link: 'jobs'},
	{text: 'Redeem Gift Cards', link: 'redeem-gift-cards'},
	{text: 'Buy Gift Cards', link: 'buy-gift-cards'},
	{text: 'Ways to Watch', link: 'ways-to-watch'},
	{text: 'Terms of Use', link: 'terms-of-use'},
	{text: 'Privacy', link: 'privacy'},
	{text: 'Cookie Preferences', link: 'cookie-preferences'},
	{text: 'Corporate Information', link: 'corporate-information'},
	{text: 'Contact Us', link: 'contact-us'},
	{text: 'Speed Test', link: 'speed-test'},
	{text: 'Legal Notices', link: 'legal-notices'},
	{text: 'Only on Netflix', link: 'only-on-netflix'},
];
